---

- name: Add ppa
  apt_repository: repo='ppa:ubuntu-elisp/ppa' state=present

- name: Update apt cache
  apt: update_cache=yes

- name: Install Emacs
  apt: pkg=emacs-snapshot state=installed

- name: Link Spacemacs config
  file: src=/home/lazywithclass/workspace/dotfiles/spacemacs/spacemacs dest=/home/lazywithclass/.spacemacs owner=lazywithclass group=lazywithclass state=link

- name: Fetch Spacemacs
  become: yes
  become_user: lazywithclass
  git: repo=https://github.com/syl20bnr/spacemacs dest=/home/lazywithclass/.emacs.d
